//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iExt.WindowsBase.Tests.Langs {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LegendAnas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LegendAnas() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iExt.WindowsBase.Tests.Langs.LegendAnas", typeof(LegendAnas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 有些人说我是英雄，这是他们说的，不是我，不过这话说得挺到位的。 的本地化字符串。
        /// </summary>
        public static string Ezreal {
            get {
                return ResourceManager.GetString("Ezreal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我于杀戮之中绽放，一如黎明中的花朵。 的本地化字符串。
        /// </summary>
        public static string Jhin {
            get {
                return ResourceManager.GetString("Jhin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有一次我试着沉默我妈，天哪！再也没有比这更糟糕的事了。 的本地化字符串。
        /// </summary>
        public static string Kassadin {
            get {
                return ResourceManager.GetString("Kassadin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 俺也是从石头里蹦出来的，为啥不是猴子呢？ 的本地化字符串。
        /// </summary>
        public static string Malphit {
            get {
                return ResourceManager.GetString("Malphit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本上，哪里都可能淹死人。 的本地化字符串。
        /// </summary>
        public static string Pyke {
            get {
                return ResourceManager.GetString("Pyke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一位大师曾经说过：“要像水一样。”那我应该是是海啸吧。 的本地化字符串。
        /// </summary>
        public static string Set {
            get {
                return ResourceManager.GetString("Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尖叫对你来说没有任何益处，但在我耳中却是美妙的音乐。 的本地化字符串。
        /// </summary>
        public static string Thres {
            get {
                return ResourceManager.GetString("Thres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 俺老孙一个跟头能翻十万八千里。 的本地化字符串。
        /// </summary>
        public static string Wukong {
            get {
                return ResourceManager.GetString("Wukong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 人们一直在往我的剑上撞。 的本地化字符串。
        /// </summary>
        public static string Yasuo {
            get {
                return ResourceManager.GetString("Yasuo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 直面暗影，找寻真理。 的本地化字符串。
        /// </summary>
        public static string Zed {
            get {
                return ResourceManager.GetString("Zed", resourceCulture);
            }
        }
    }
}
